Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,4 +1,113 @@
 #!/usr/bin/env bash
-echo "-----&gt; Installing .Net"
-# change to the the BUILD_DIR ($1)
-cd $1
+# bin/compile <build-dir> <cache-dir>
+
+# fail fast
+set -e
+
+if [ $STACK != "cedar-14" ]; then
+	echo "Stack ${STACK} not supported" && exit 1
+fi
+
+BUILD_DIR=$1
+CACHE_DIR=$2
+ENV_DIR=$3
+# This is where the buildpack is stored
+BUILDPACK_DIR=`cd $(dirname $0); cd ..; pwd`
+
+: ${LIBUV_VERSION:="1.8.0"}
+: ${DNVM_BRANCH:="dev"}
+: ${DNX_VERSION:="latest"}
+
+if [ -n "$BUILD_DEBUG" ]; then
+	DNU_FLAGS=""
+	echo "DNX_VERSION: ${DNX_VERSION}"
+	echo "DNVM_BRANCH: ${DNVM_BRANCH}"
+else
+	DNU_FLAGS="--quiet"
+fi
+
+if [ -n "$UNSTABLE_TOOLCHAIN" ]; then
+	DNVM_FLAGS="-u"
+else
+	DNVM_FLAGS=""
+fi
+
+SRC_DIR=`mktemp -d`
+# Move the app source code into temporary src dir using subshell to not leak shopt
+(
+	shopt -s dotglob
+	mv ${BUILD_DIR}/* ${SRC_DIR}
+)
+
+mkdir -p ${CACHE_DIR}
+
+
+export PATH="/app/aspnet/bin:${PATH}"
+export LD_LIBRARY_PATH="/app/aspnet/lib:${LD_LIBRARY_PATH}"
+
+mozroots --import --sync --quiet
+cp -r ~/.config ${BUILD_DIR}/.
+
+
+# Install DNX
+# TODO: consider making this not dependent on GitHub being up
+touch ~/.profile
+curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
+
+export DNVM_RUNTIME_LOCAL_CACHE="/app/.dnx"
+export DNVM_RUNTIME_CACHE_LOCATION="${CACHE_DIR}/dnx/runtimes"
+mkdir -p ${DNVM_RUNTIME_LOCAL_CACHE}
+mkdir -p ${DNVM_RUNTIME_CACHE_LOCATION}
+ln -s ${DNVM_RUNTIME_CACHE_LOCATION} ${DNVM_RUNTIME_LOCAL_CACHE}/runtimes
+
+# TODO: extract DNX version from global.json
+dnvm install $DNX_VERSION $DNVM_FLAGS -a default
+
+# Add DNX to the build output
+DNX_BUILD_LOCATION=${BUILD_DIR}/.dnx/runtimes/
+mkdir -p ${DNX_BUILD_LOCATION}
+cp -r ~/.dnx/runtimes/`dnvm alias default` ${DNX_BUILD_LOCATION}
+
+DEPLOYMENT_FILE_LOCATION=${SRC_DIR}/.deployment
+if [ -n "$PROJECT" ]; then
+	PROJECT_JSON_FILE=${SRC_DIR}/${PROJECT}
+	echo "Project file configured in PROJECT environment variable"
+elif [ -e ${DEPLOYMENT_FILE_LOCATION} ]; then
+	PROJECT_JSON_FILE=${SRC_DIR}/$(awk -F "=" '/project/ {print $2}' ${DEPLOYMENT_FILE_LOCATION} | tr -d ' ')
+	echo "Project file configured in .deployment file"
+else
+	PROJECT_JSON_FILES=$(find ${SRC_DIR}/. -maxdepth 3 -iname "project.json")
+	printf 'Found %s project.json files\n' $(echo "$PROJECT_JSON_FILES" | wc -l | tr -d ' ')
+	PROJECT_JSON_FILE=$(echo "$PROJECT_JSON_FILES" | head -1)
+fi
+echo "Building ${PROJECT_JSON_FILE}"
+
+export DNU_LOCAL_CACHE="/app/.local/share/dnu"
+export DNU_CACHE_LOCATION="${CACHE_DIR}/dnu/cache"
+mkdir -p ${DNU_LOCAL_CACHE}
+mkdir -p ${DNU_CACHE_LOCATION}
+ln -s ${DNU_CACHE_LOCATION} ${DNU_LOCAL_CACHE}/cache 
+
+dnu restore $DNU_FLAGS ${PROJECT_JSON_FILE}
+
+dnu publish --out ${BUILD_DIR} $DNU_FLAGS --no-source --configuration Release ${PROJECT_JSON_FILE}
+
+# Clean out core-stuff that we don't need in the slug
+find ${BUILD_DIR} -iname dnxcore50 -print0 | xargs -r -0 rm --
+
+mkdir -p ${BUILD_DIR}/.profile.d
+cp -n ${BUILDPACK_DIR}/.profile.d/* ${BUILD_DIR}/.profile.d/
+
+curl https://github.com/friism/libuv-builder/releases/download/v${LIBUV_VERSION}/libuv-${LIBUV_VERSION}.tar.gz -sL \
+	 | tar xz -C ${BUILD_DIR}
+if [ -e ${SRC_DIR}/Procfile ]; then
+	cp ${SRC_DIR}/Procfile ${BUILD_DIR}
+else
+	ROOTS=`cd ${BUILD_DIR}; find approot/packages/ -name root`
+	if [ $( echo "${ROOTS}" | wc -l ) -gt 0 ]; then
+	APP_ROOT=$(echo "$ROOTS" | head -1)
+	cat << EOT >> ${BUILD_DIR}/Procfile
+web: ./kestrel --server.urls http://+:\$PORT
+EOT
+	fi
+fi
